version: '3.8'
services:
  web:
    container_name: php-apache
    build: ./conf
    volumes:
      - ./conf/sri.asir4all.ss.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/contrase単a:/etc/apache2/contrase単a
      - ./conf/contrase単a2:/etc/apache2/contrase単a2
      - ./web:/var/www/html/
    ports:
      - 8181:80
